### ISSUE TITLE
TypeError:  Cannot set property 'cooldown' of undefined

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips#122]
```
2021-06-02T09:07:02: TypeError: Cannot set property 'cooldown' of undefined
2021-06-02T09:07:02:     at MonitorTwitchChat.removeCooldownForStreamer (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:94:67)
2021-06-02T09:07:02:     at MonitorTwitchChat.<anonymous> (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:89:36)
2021-06-02T09:07:02:     at listOnTimeout (node:internal/timers:557:17)
2021-06-02T09:07:02:     at processTimers (node:internal/timers:500:7)
```

**Comment by GastonGit** [comment]
Fixed by: https://github.com/GastonGit/Hot-Twitch-Clips/pull/123/commits/c910923509c5ec1349020d111c9d7ab29693f4b5
