### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips#130]
`
1|HotClips | 2021-06-30T16:37:21: TypeError: Cannot read property 'forEach' of undefined
1|HotClips | 2021-06-30T16:37:21:     at MonitorTwitchChat.requestStreams (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:132:33)
1|HotClips | 2021-06-30T16:37:21:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|HotClips | 2021-06-30T16:37:21:     at async MonitorTwitchChat.updateStreamList (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:121:27)
1|HotClips | 2021-06-30T16:37:21:     at async HotClipsController.setupConnection (.../Hot-Twitch-Clips/server/lib/HotClipsController.js:49:9)
`

**Comment by GastonGit** [comment]
Reason for error is an expired access token (https://github.com/GastonGit/Hot-Twitch-Clips/issues/82)

**Comment by GastonGit** [comment]
The app is working after updating access token.
Closing with references to https://github.com/GastonGit/Hot-Twitch-Clips/issues/131 and https://github.com/GastonGit/Hot-Twitch-Clips/issues/82
