### ISSUE TITLE
undefined data error

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips#138]
`1|HotClips - server  | 2021-08-31T09:14:27: > server@0.0.1 start
1|HotClips - server  | 2021-08-31T09:14:27: > node bin/www
1|HotClips - server  | 2021-08-31T09:14:27:
1|HotClips - server  | 2021-08-31T09:14:27:
1|HotClips - server  | 2021-08-31T09:14:27: --- HotClipsController :: Using settings from config.json
1|HotClips - server  | 2021-08-31T09:14:27:
1|HotClips - server  | 2021-08-31T09:14:27: /../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:132
1|HotClips - server  | 2021-08-31T09:14:27:             fetchedStreams.data.forEach(function(streamer){
1|HotClips - server  | 2021-08-31T09:14:27:                                 ^
1|HotClips - server  | 2021-08-31T09:14:27:
1|HotClips - server  | 2021-08-31T09:14:27: TypeError: Cannot read property 'forEach' of undefined
1|HotClips - server  | 2021-08-31T09:14:27:     at MonitorTwitchChat.requestStreams (/../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:132:33)
1|HotClips - server  | 2021-08-31T09:14:27:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|HotClips - server  | 2021-08-31T09:14:27:     at async MonitorTwitchChat.updateStreamList (/../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:121:27)
1|HotClips - server  | 2021-08-31T09:14:27:     at async HotClipsController.setupConnection (/../Hot-Twitch-Clips/server/lib/HotClipsController.js:49:9)
PM2                  | App [HotClips - server:1] exited with code [1] via signal [SIGINT]
`

**Comment by GastonGit** [comment]
Server had not been updated. After updating, the server shows the current error "Error: Current App Access Token is invalid".  More info: https://github.com/GastonGit/Hot-Twitch-Clips/issues/82
