### ISSUE TITLE
Client tests warning: unstable_flushDiscreteUpdates

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips#151]
```
  PASS  src/__tests__/App.test.tsx
  √ renders unmute button image (99 ms)

  console.error
    Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.
        at video
        at Video (..\HotTwitchClips\_source\client\src\components\Video.tsx:14:9)
        at div
        at VideoPlayer (..\HotTwitchClips\_source\client\src\components\VideoPlayer.tsx:7:9)
        at div
        at div
        at App (..\HotTwitchClips\_source\client\src\components\App.tsx:7:9)

```

**Comment by GastonGit** [comment]
Warning/error is caused by "muted" tag in a video element

**Comment by GastonGit** [comment]
Fixed by: https://github.com/GastonGit/Hot-Twitch-Clips/commit/8abe3998d28346ca31034ab55499e541aa094c27
