### ISSUE TITLE
Chai testing not working with async code?

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips#17]
When creating tests for two new async methods in TwitchClient, chai acts weird.
Example: 
"expect(TwitchClient.getBroadcasterID).to.throw();" works when the method is not async. But if changed to async mocha returns:
AssertionError: expected [Function: getBroadcasterID] to throw an error
at Context.<anonymous> (test\testTwitchClient.js:47:59)
at processImmediate (internal/timers.js:456:21)

During research I found that chai does not natively  support async code.
This would mean that existing tests that are testing async methods are not actually working correctly.

Further research and testing is required.

**Comment by GastonGit** [comment]
Good info regarding testing async code both without chai and with chas-as-promised: https://stackoverflow.com/questions/26571328/how-do-i-properly-test-promises-with-mocha-and-chai

Examples can be found in TwitchClient's test from: https://github.com/GastonGit/Hot-Twitch-Clips/commit/81b53d4fc10612de964b30a9c53f4a52c3ccc5c9

**Comment by GastonGit** [comment]
Good info regarding testing async code both without chai and with chai-as-promised: https://stackoverflow.com/questions/26571328/how-do-i-properly-test-promises-with-mocha-and-chai

Examples can be found in TwitchClient's tests from: 81b53d4

This issue is considered closed for now.
