### ISSUE TITLE
Rare TypeError during clip creation

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips#75]
```
(node:10444) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'thumbnail_url' of undefined
    at Clipper.getVideoUrl (...\server\lib\Clipper.js:73:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async HotClipsController.<anonymous> (...\server\lib\HotClipsController.js:86:30)
(node:10444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by GastonGit** [comment]
Completed with: 9883180ca801fdc7006a16d53c27e840ef4ff655
